#! /bin/sh

name=plasma-wayland-protocols
version=1.18.0
revision=1
tarball_url="https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-${version}.tar.xz"
tarball_blake2b="25ad324eab3438da9bdd4c014b469b8fcedc4b1c82e6c19bd79aa16f6180cb9fbf0134e89354b854caf25ae31e5e4a4da8dfb4207ac2116e5a9c95dee76cda87"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs ecm"

configure() {
    cmake_configure \
		-Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
